language: node_js
cache:
  directories:
    - ~/.npm
node_js:
  - '9'
git:
  depth: 3
script:
  - yarn build
  - echo 'https://github.com/pfcardona/curriculumVitae ' > public/CNAME
deploy:

  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
    branch: develop
